apiVersion: v1
entries:
  common:
  - annotations:
      category: Infrastructure
      licenses: Apache-2.0
    apiVersion: v2
    appVersion: 2.26.0
    created: "2024-11-19T08:36:36.123631396+01:00"
    description: A Library Helm Chart for grouping common logic between bitnami charts.
      This chart is not deployable by itself.
    digest: c12c90fc1f36ae1b4c345065880c81b065c1e1d42d1f6e8adc48a8c1b1126e2b
    home: https://bitnami.com
    icon: https://bitnami.com/downloads/logos/bitnami-mark.png
    keywords:
    - common
    - helper
    - template
    - function
    - bitnami
    maintainers:
    - name: Broadcom, Inc. All Rights Reserved.
      url: https://github.com/bitnami/charts
    name: common
    sources:
    - https://github.com/bitnami/charts/tree/main/bitnami/common
    type: library
    urls:
    - charts/common-2.26.0.tgz
    version: 2.26.0
  postgresql:
  - annotations:
      category: Database
      images: |
        - name: os-shell
          image: docker.io/bitnami/os-shell:11-debian-11-r90
        - name: postgres-exporter
          image: docker.io/bitnami/postgres-exporter:0.14.0-debian-11-r15
        - name: postgresql
          image: docker.io/bitnami/postgresql:16.0.0-debian-11-r13
      licenses: Apache-2.0
    apiVersion: v2
    appVersion: 16.0.0
    created: "2024-11-19T08:36:36.132722033+01:00"
    dependencies:
    - name: common
      repository: oci://registry-1.docker.io/bitnamicharts
      tags:
      - bitnami-common
      version: 2.x.x
    description: PostgreSQL (Postgres) is an open source object-relational database
      known for reliability and data integrity. ACID-compliant, it supports foreign
      keys, joins, views, triggers and stored procedures.
    digest: f4921111dcca536f7d8354de061e85a52d37d58638e79ebb2c163fb5f1ba8452
    home: https://bitnami.com
    icon: https://bitnami.com/assets/stacks/postgresql/img/postgresql-stack-220x234.png
    keywords:
    - postgresql
    - postgres
    - database
    - sql
    - replication
    - cluster
    maintainers:
    - name: VMware, Inc.
      url: https://github.com/bitnami/charts
    name: postgresql
    sources:
    - https://github.com/bitnami/charts/tree/main/bitnami/postgresql
    urls:
    - charts/postgresql-13.1.5.tgz
    version: 13.1.5
generated: "2024-11-19T08:36:36.121510529+01:00"
