{{- if ((.Values.apiserver).serviceMonitor).create -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels: {{- include "backend.labels.standard" . | nindent 4 }}
    prometheus: pitc
    metrics-monitoring: "true"
  name: metrics-monitoring
  namespace: {{ .Release.Namespace }}
spec:
  endpoints:
    - interval: 30s
      port: metrics
      scheme: http
      path: /metrics
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/name: deptrack
      app.kubernetes.io/component: backend
{{- end -}}
