apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}-postgresql
  labels: {{- include "backend.labels.standard" . | nindent 4 }}
  {{- with .Values.apiserver.annotations }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  data:
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: {{ .Values.externalSecrets.postgresql }}
        property: postgresql-postgres-password
      secretKey: postgresql-postgres-password
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: {{ .Values.externalSecrets.postgresql }}
        property: postgresql-password
      secretKey: postgresql-password
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: vault
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: deptrack-postgresql
